# ========================================
# Docker Compose для разработки
# Использование: docker-compose -f docker-compose.dev.yml up
# ========================================

version: '3.8'

services:
  bot:
    build:
      context: .
      dockerfile: Dockerfile
      target: builder  # Используем builder stage с dev tools
    container_name: telegram_repair_bot_dev
    restart: "no"
    env_file:
      - .env
    environment:
      - DATABASE_PATH=/app/data/bot_database.db
      - LOG_LEVEL=DEBUG
      - PYTHONUNBUFFERED=1
    volumes:
      # Монтируем весь проект для hot-reload
      - .:/app
      - ./data:/app/data
      - ./logs:/app/logs
    ports:
      # Открываем порт для отладки (если нужно)
      - "5678:5678"
    depends_on:
      - redis
    networks:
      - bot_network
    command: python bot.py
    stdin_open: true
    tty: true

  redis:
    image: redis:7-alpine
    container_name: telegram_bot_redis_dev
    ports:
      - "6379:6379"
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

