# ========================================
# Docker Compose для миграций
# Использование: docker compose -f docker/docker-compose.migrate.yml run migrate
# ========================================

version: '3.8'

services:
  migrate:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_bot_migrate
    env_file:
      - ../.env
    environment:
      - DATABASE_PATH=/app/data/bot_database.db
    volumes:
      - ../data:/app/data
      - ../migrations:/app/migrations
      - ../alembic.ini:/app/alembic.ini
    command: alembic upgrade head
    networks:
      - bot_network

networks:
  bot_network:
    driver: bridge

