version: '3.8'

# ========================================
# SERVICES
# ========================================

services:
  # Telegram Bot
  bot:
    build:
      context: ..
      dockerfile: docker/Dockerfile
    container_name: telegram_repair_bot
    restart: unless-stopped
    env_file:
      - ../.env
    environment:
      # Database
      - DATABASE_PATH=/app/data/bot_database.db
    volumes:
      # Монтируем базу данных
      - ../data:/app/data
      # Монтируем логи
      - ../logs:/app/logs
      # Монтируем backups
      - ../backups:/app/backups
    networks:
      - bot_network
    healthcheck:
      test: ["CMD", "python", "-c", "import os; exit(0 if os.path.exists('/app/data/bot_database.db') else 1)"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 5s
    logging:
      driver: "json-file"
      options:
        max-size: "10m"
        max-file: "3"

# ========================================
# NETWORKS
# ========================================

networks:
  bot_network:
    driver: bridge

# ========================================
# VOLUMES
# ========================================

# Локальные volumes не нужны, используем bind mounts
