"""rename_master_reports_archive_table

Revision ID: 10ff87cace39
Revises: 010_create_master_reports_archive
Create Date: 2025-10-21 14:13:49.661124

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '10ff87cace39'
down_revision: Union[str, None] = '010_create_master_reports_archive'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('master_report_archives',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('master_id', sa.Integer(), nullable=False),
    sa.Column('period_start', sa.DateTime(), nullable=False),
    sa.Column('period_end', sa.DateTime(), nullable=False),
    sa.Column('file_path', sa.String(length=500), nullable=False),
    sa.Column('file_name', sa.String(length=255), nullable=False),
    sa.Column('file_size', sa.Integer(), nullable=False),
    sa.Column('total_orders', sa.Integer(), nullable=False),
    sa.Column('active_orders', sa.Integer(), nullable=False),
    sa.Column('completed_orders', sa.Integer(), nullable=False),
    sa.Column('total_revenue', sa.Float(), nullable=False),
    sa.Column('created_at', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_report_archives', schema=None) as batch_op:
        batch_op.create_index('idx_master_report_archives_created_at', ['created_at'], unique=False)
        batch_op.create_index('idx_master_report_archives_master_id', ['master_id'], unique=False)
        batch_op.create_index('idx_master_report_archives_period', ['period_start', 'period_end'], unique=False)

    with op.batch_alter_table('master_reports_archive', schema=None) as batch_op:
        batch_op.drop_index('idx_master_reports_created')
        batch_op.drop_index('idx_master_reports_period')

    op.drop_table('master_reports_archive')
    with op.batch_alter_table('order_reports', schema=None) as batch_op:
        batch_op.drop_index('idx_order_reports_closed_at')
        batch_op.drop_index('idx_order_reports_master_id')
        batch_op.drop_index('idx_order_reports_order_id')

    op.drop_table('order_reports')
    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               nullable=False)
        batch_op.drop_index('idx_financial_reports_period')
        batch_op.drop_index('idx_financial_reports_type')

    with op.batch_alter_table('master_financial_reports', schema=None) as batch_op:
        # Удаляем только индексы, внешние ключи оставляем как есть
        batch_op.drop_index('idx_master_reports_master_id')
        batch_op.drop_index('idx_master_reports_report_id')

    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=False,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_masters_active_approved', ['is_active', 'is_approved'], unique=False)
        batch_op.create_index('idx_masters_work_chat', ['work_chat_id'], unique=False)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('changed_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_status_history_changed_at', ['changed_at'], unique=False)
        batch_op.create_index('idx_status_history_changed_by', ['changed_by'], unique=False)
        batch_op.create_index('idx_status_history_order', ['order_id', 'changed_at'], unique=False)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'NEW'"))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.create_index('idx_orders_financial', ['status', 'total_amount'], unique=False)
        batch_op.create_index('idx_orders_master_status', ['assigned_master_id', 'status'], unique=False)
        batch_op.create_index('idx_orders_period', ['updated_at', 'status'], unique=False)
        batch_op.create_index('idx_orders_review', ['has_review', 'status'], unique=False)
        batch_op.create_index('idx_orders_status_created', ['status', 'created_at'], unique=False)

    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               nullable=False,
               existing_server_default=sa.text("'UNKNOWN'"))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))

    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade database schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'UNKNOWN'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_status_created')
        batch_op.drop_index('idx_orders_review')
        batch_op.drop_index('idx_orders_period')
        batch_op.drop_index('idx_orders_master_status')
        batch_op.drop_index('idx_orders_financial')
        batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'NEW'"))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.drop_index('idx_status_history_order')
        batch_op.drop_index('idx_status_history_changed_by')
        batch_op.drop_index('idx_status_history_changed_at')
        batch_op.alter_column('changed_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.drop_index('idx_masters_work_chat')
        batch_op.drop_index('idx_masters_active_approved')
        batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('master_financial_reports', schema=None) as batch_op:
        # Восстанавливаем только индексы
        batch_op.create_index('idx_master_reports_report_id', ['report_id'], unique=False)
        batch_op.create_index('idx_master_reports_master_id', ['master_id'], unique=False)

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.create_index('idx_financial_reports_type', ['report_type'], unique=False)
        batch_op.create_index('idx_financial_reports_period', ['period_start', 'period_end'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.alter_column('timestamp',
               existing_type=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('order_reports',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('order_id', sa.INTEGER(), nullable=False),
    sa.Column('equipment_type', sa.TEXT(), nullable=False),
    sa.Column('client_name', sa.TEXT(), nullable=False),
    sa.Column('client_address', sa.TEXT(), nullable=True),
    sa.Column('master_id', sa.INTEGER(), nullable=True),
    sa.Column('master_name', sa.TEXT(), nullable=True),
    sa.Column('dispatcher_id', sa.INTEGER(), nullable=True),
    sa.Column('dispatcher_name', sa.TEXT(), nullable=True),
    sa.Column('total_amount', sa.REAL(), nullable=False),
    sa.Column('materials_cost', sa.REAL(), nullable=False),
    sa.Column('master_profit', sa.REAL(), nullable=False),
    sa.Column('company_profit', sa.REAL(), nullable=False),
    sa.Column('out_of_city', sa.BOOLEAN(), nullable=True),
    sa.Column('has_review', sa.BOOLEAN(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), nullable=False),
    sa.Column('closed_at', sa.DATETIME(), nullable=False),
    sa.Column('completion_time_hours', sa.REAL(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('order_reports', schema=None) as batch_op:
        batch_op.create_index('idx_order_reports_order_id', ['order_id'], unique=False)
        batch_op.create_index('idx_order_reports_master_id', ['master_id'], unique=False)
        batch_op.create_index('idx_order_reports_closed_at', ['closed_at'], unique=False)

    op.create_table('master_reports_archive',
    sa.Column('id', sa.INTEGER(), nullable=False),
    sa.Column('master_id', sa.INTEGER(), nullable=False),
    sa.Column('period_start', sa.DATETIME(), nullable=False),
    sa.Column('period_end', sa.DATETIME(), nullable=False),
    sa.Column('file_path', sa.VARCHAR(length=500), nullable=False),
    sa.Column('file_name', sa.VARCHAR(length=255), nullable=False),
    sa.Column('file_size', sa.INTEGER(), nullable=True),
    sa.Column('total_orders', sa.INTEGER(), nullable=True),
    sa.Column('active_orders', sa.INTEGER(), nullable=True),
    sa.Column('completed_orders', sa.INTEGER(), nullable=True),
    sa.Column('total_revenue', sa.FLOAT(), nullable=True),
    sa.Column('created_at', sa.DATETIME(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('notes', sa.TEXT(), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('master_reports_archive', schema=None) as batch_op:
        batch_op.create_index('idx_master_reports_period', ['period_start', 'period_end'], unique=False)
        batch_op.create_index('idx_master_reports_created', ['created_at'], unique=False)

    with op.batch_alter_table('master_report_archives', schema=None) as batch_op:
        batch_op.drop_index('idx_master_report_archives_period')
        batch_op.drop_index('idx_master_report_archives_master_id')
        batch_op.drop_index('idx_master_report_archives_created_at')

    op.drop_table('master_report_archives')
    # ### end Alembic commands ###
