"""add_order_reports_table

Revision ID: 77f5626ac688
Revises: 4734f51bfd4b
Create Date: 2025-11-03 17:15:55.116398

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '77f5626ac688'
down_revision: Union[str, None] = '4734f51bfd4b'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Создаем таблицу order_reports если её нет
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    if not inspector.has_table('order_reports'):
        op.create_table(
            'order_reports',
            sa.Column('id', sa.Integer(), nullable=False, autoincrement=True),
            sa.Column('order_id', sa.Integer(), nullable=False),
            sa.Column('equipment_type', sa.String(length=255), nullable=False),
            sa.Column('client_name', sa.String(length=255), nullable=False),
            sa.Column('client_address', sa.String(length=500), nullable=True),
            sa.Column('master_id', sa.Integer(), nullable=True),
            sa.Column('master_name', sa.String(length=255), nullable=True),
            sa.Column('dispatcher_id', sa.Integer(), nullable=True),
            sa.Column('dispatcher_name', sa.String(length=255), nullable=True),
            sa.Column('total_amount', sa.Float(), nullable=True, server_default='0.0'),
            sa.Column('materials_cost', sa.Float(), nullable=True, server_default='0.0'),
            sa.Column('master_profit', sa.Float(), nullable=True, server_default='0.0'),
            sa.Column('company_profit', sa.Float(), nullable=True, server_default='0.0'),
            sa.Column('out_of_city', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('has_review', sa.Integer(), nullable=True, server_default='0'),
            sa.Column('created_at', sa.DateTime(), nullable=True),
            sa.Column('closed_at', sa.DateTime(), nullable=True),
            sa.Column('completion_time_hours', sa.Float(), nullable=True),
            sa.PrimaryKeyConstraint('id'),
        )
        print("[OK] Таблица order_reports создана")
    else:
        print("[SKIP] Таблица order_reports уже существует")
    
    # Удаляем master_archives только если существует
    try:
        from sqlalchemy import inspect as _insp2
        _ins = _insp2(op.get_bind())
        if _ins.has_table('master_archives'):
            op.drop_table('master_archives')
            print('[OK] Таблица master_archives удалена')
        else:
            print('[SKIP] Таблица master_archives не существует')
    except Exception as _e:
        print(f'[WARN] Пропускаем удаление master_archives: {_e}')
    # Подготовим информацию о столбцах/индексах audit_log
    audit_log_columns = {c['name'] for c in inspector.get_columns('audit_log')} if inspector.has_table('audit_log') else set()
    audit_log_indexes = {i['name'] for i in inspector.get_indexes('audit_log')} if inspector.has_table('audit_log') else set()

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
        batch_op.alter_column('action',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
        batch_op.alter_column('timestamp',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
        if 'idx_audit_log_deleted_at' not in audit_log_indexes:
            batch_op.create_index('idx_audit_log_deleted_at', ['deleted_at'], unique=False)
        if 'idx_audit_timestamp' not in audit_log_indexes:
            batch_op.create_index('idx_audit_timestamp', ['timestamp'], unique=False)
        if 'version' in audit_log_columns:
            batch_op.drop_column('version')

    if inspector.has_table('entity_history'):
        entity_history_columns = {c['name'] for c in inspector.get_columns('entity_history')}
        with op.batch_alter_table('entity_history', schema=None) as batch_op:
            if 'version' in entity_history_columns:
                batch_op.drop_column('version')
            if 'deleted_at' in entity_history_columns:
                batch_op.drop_column('deleted_at')

    if inspector.has_table('financial_reports'):
        financial_reports_columns = {c['name'] for c in inspector.get_columns('financial_reports')}
        financial_reports_indexes = {i['name'] for i in inspector.get_indexes('financial_reports')}
        with op.batch_alter_table('financial_reports', schema=None) as batch_op:
            batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
            batch_op.alter_column('report_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
            batch_op.alter_column('period_start',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
            batch_op.alter_column('period_end',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               existing_nullable=True)
            batch_op.alter_column('total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_materials_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_net_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_company_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_master_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('average_check',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('created_at',
               existing_type=sa.TEXT(),
               type_=sa.DateTime(),
               nullable=False)
            if 'idx_financial_reports_period' in financial_reports_indexes:
                batch_op.drop_index('idx_financial_reports_period')
            if 'idx_financial_reports_type' in financial_reports_indexes:
                batch_op.drop_index('idx_financial_reports_type')
            if 'version' in financial_reports_columns:
                batch_op.drop_column('version')
            if 'deleted_at' in financial_reports_columns:
                batch_op.drop_column('deleted_at')

    if inspector.has_table('master_financial_reports'):
        master_financial_reports_columns = {c['name'] for c in inspector.get_columns('master_financial_reports')}
        master_financial_reports_indexes = {i['name'] for i in inspector.get_indexes('master_financial_reports')}
        with op.batch_alter_table('master_financial_reports', schema=None) as batch_op:
            batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
            batch_op.alter_column('master_id',
               existing_type=sa.INTEGER(),
               nullable=True)
            batch_op.alter_column('master_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
            batch_op.alter_column('total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_materials_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_net_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_master_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('total_company_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            batch_op.alter_column('average_check',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
            if 'idx_master_reports_master_id' in master_financial_reports_indexes:
                batch_op.drop_index('idx_master_reports_master_id')
            if 'idx_master_reports_report_id' in master_financial_reports_indexes:
                batch_op.drop_index('idx_master_reports_report_id')
            # Создаем внешние ключи с явными именами
            batch_op.create_foreign_key('fk_master_financial_reports_report_id', 'financial_reports', ['report_id'], ['id'])
            batch_op.create_foreign_key('fk_master_financial_reports_master_id', 'masters', ['master_id'], ['id'])
            if 'version' in master_financial_reports_columns:
                batch_op.drop_column('version')
            if 'deleted_at' in master_financial_reports_columns:
                batch_op.drop_column('deleted_at')

    if inspector.has_table('master_report_archives'):
        master_report_archives_columns = {c['name'] for c in inspector.get_columns('master_report_archives')}
        with op.batch_alter_table('master_report_archives', schema=None) as batch_op:
            if 'version' in master_report_archives_columns:
                batch_op.drop_column('version')
            if 'deleted_at' in master_report_archives_columns:
                batch_op.drop_column('deleted_at')

    if inspector.has_table('masters'):
        masters_columns = {c['name']: c for c in inspector.get_columns('masters')}
        masters_indexes = {i['name'] for i in inspector.get_indexes('masters')}
        
        # Создаем индексы напрямую, без изменения таблицы
        # Это безопаснее, так как не требует пересоздания таблицы
        if 'idx_masters_active_approved' not in masters_indexes:
            if 'is_active' in masters_columns and 'is_approved' in masters_columns:
                try:
                    op.create_index('idx_masters_active_approved', 'masters', ['is_active', 'is_approved'], unique=False)
                    print("[OK] Создан индекс idx_masters_active_approved")
                except Exception as e:
                    print(f"[WARN] Не удалось создать индекс idx_masters_active_approved: {e}")
        
        if 'idx_masters_deleted_at' not in masters_indexes:
            if 'deleted_at' in masters_columns:
                try:
                    op.create_index('idx_masters_deleted_at', 'masters', ['deleted_at'], unique=False)
                    print("[OK] Создан индекс idx_masters_deleted_at")
                except Exception as e:
                    print(f"[WARN] Не удалось создать индекс idx_masters_deleted_at: {e}")
        
        if 'work_chat_id' in masters_columns and 'idx_masters_work_chat' not in masters_indexes:
            try:
                op.create_index('idx_masters_work_chat', 'masters', ['work_chat_id'], unique=False)
                print("[OK] Создан индекс idx_masters_work_chat")
            except Exception as e:
                print(f"[WARN] Не удалось создать индекс idx_masters_work_chat: {e}")
        
        print("[SKIP] Таблица masters - индексы проверены и созданы при необходимости")

    if inspector.has_table('order_group_messages'):
        order_group_messages_columns = {c['name'] for c in inspector.get_columns('order_group_messages')}
        with op.batch_alter_table('order_group_messages', schema=None) as batch_op:
            if 'version' in order_group_messages_columns:
                batch_op.drop_column('version')

    if inspector.has_table('order_status_history'):
        order_status_history_columns = {c['name'] for c in inspector.get_columns('order_status_history')}
        with op.batch_alter_table('order_status_history', schema=None) as batch_op:
            batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
            batch_op.alter_column('old_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=True)
            batch_op.alter_column('new_status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               existing_nullable=False)
            batch_op.alter_column('changed_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
            batch_op.create_index('idx_status_history_changed_at', ['changed_at'], unique=False)
            batch_op.create_index('idx_status_history_changed_by', ['changed_by'], unique=False)
            batch_op.create_index('idx_status_history_order', ['order_id', 'changed_at'], unique=False)
            if 'version' in order_status_history_columns:
                batch_op.drop_column('version')
            if 'deleted_at' in order_status_history_columns:
                batch_op.drop_column('deleted_at')

    if inspector.has_table('orders'):
        with op.batch_alter_table('orders', schema=None) as batch_op:
            batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
            batch_op.alter_column('equipment_type',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
            batch_op.alter_column('client_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=False)
            batch_op.alter_column('client_phone',
               existing_type=sa.TEXT(),
               type_=sa.String(length=20),
               existing_nullable=False)
            batch_op.alter_column('status',
               existing_type=sa.TEXT(),
               type_=sa.String(length=50),
               nullable=False,
               existing_server_default=sa.text("'NEW'"))
            batch_op.alter_column('scheduled_time',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
            batch_op.alter_column('total_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
            batch_op.alter_column('materials_cost',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
            batch_op.alter_column('master_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
            batch_op.alter_column('company_profit',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
            batch_op.alter_column('has_review',
               existing_type=sa.INTEGER(),
               type_=sa.Boolean(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
            batch_op.alter_column('estimated_completion_date',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               existing_nullable=True)
            batch_op.alter_column('prepayment_amount',
               existing_type=sa.REAL(),
               type_=sa.Float(),
               existing_nullable=True)
            batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
            batch_op.alter_column('updated_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
            batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
            batch_op.create_index('idx_orders_deleted_at', ['deleted_at'], unique=False)
            batch_op.create_index('idx_orders_financial', ['status', 'total_amount'], unique=False)
            batch_op.create_index('idx_orders_master_status', ['assigned_master_id', 'status'], unique=False)
            batch_op.create_index('idx_orders_period', ['updated_at', 'status'], unique=False)
            batch_op.create_index('idx_orders_review', ['has_review', 'status'], unique=False)
            batch_op.create_index('idx_orders_status_created', ['status', 'created_at'], unique=False)

    if inspector.has_table('users'):
        with op.batch_alter_table('users', schema=None) as batch_op:
            batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=False,
               autoincrement=True)
            batch_op.alter_column('username',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
            batch_op.alter_column('first_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
            batch_op.alter_column('last_name',
               existing_type=sa.TEXT(),
               type_=sa.String(length=255),
               existing_nullable=True)
            batch_op.alter_column('role',
               existing_type=sa.TEXT(),
               type_=sa.String(length=100),
               nullable=False,
               existing_server_default=sa.text("'UNKNOWN'"))
            batch_op.alter_column('created_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               nullable=False,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
            batch_op.alter_column('deleted_at',
               existing_type=sa.TIMESTAMP(),
               type_=sa.DateTime(),
               existing_nullable=True)
            batch_op.create_index('idx_users_deleted_at', ['deleted_at'], unique=False)

    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    
    # Удаляем таблицу order_reports если она существует
    from sqlalchemy import inspect
    bind = op.get_bind()
    inspector = inspect(bind)
    
    if inspector.has_table('order_reports'):
        op.drop_table('order_reports')
        print("[OK] Таблица order_reports удалена")
    else:
        print("[SKIP] Таблица order_reports не существует")
    
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_index('idx_users_deleted_at')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('role',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'UNKNOWN'"))
        batch_op.alter_column('last_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('first_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('username',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('orders', schema=None) as batch_op:
        batch_op.drop_index('idx_orders_status_created')
        batch_op.drop_index('idx_orders_review')
        batch_op.drop_index('idx_orders_period')
        batch_op.drop_index('idx_orders_master_status')
        batch_op.drop_index('idx_orders_financial')
        batch_op.drop_index('idx_orders_deleted_at')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('updated_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('prepayment_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('estimated_completion_date',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('has_review',
               existing_type=sa.Boolean(),
               type_=sa.INTEGER(),
               existing_nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('company_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('master_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('materials_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=True)
        batch_op.alter_column('scheduled_time',
               existing_type=sa.String(length=100),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               nullable=True,
               existing_server_default=sa.text("'NEW'"))
        batch_op.alter_column('client_phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('client_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('equipment_type',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('order_status_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
        batch_op.drop_index('idx_status_history_order')
        batch_op.drop_index('idx_status_history_changed_by')
        batch_op.drop_index('idx_status_history_changed_at')
        batch_op.alter_column('changed_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('new_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('old_status',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('order_group_messages', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('masters', schema=None) as batch_op:
        batch_op.drop_index('idx_masters_work_chat')
        batch_op.drop_index('idx_masters_deleted_at')
        batch_op.drop_index('idx_masters_active_approved')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('is_approved',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('0'))
        batch_op.alter_column('is_active',
               existing_type=sa.BOOLEAN(),
               nullable=True,
               existing_server_default=sa.text('1'))
        batch_op.alter_column('specialization',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('phone',
               existing_type=sa.String(length=20),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('master_report_archives', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('master_financial_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_foreign_key(None, 'masters', ['master_id'], ['id'], ondelete='CASCADE')
        batch_op.create_foreign_key(None, 'financial_reports', ['report_id'], ['id'], ondelete='CASCADE')
        batch_op.create_index('idx_master_reports_report_id', ['report_id'], unique=False)
        batch_op.create_index('idx_master_reports_master_id', ['master_id'], unique=False)
        batch_op.alter_column('average_check',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_company_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_master_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_net_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_materials_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('master_name',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('master_id',
               existing_type=sa.INTEGER(),
               nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('financial_reports', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
        batch_op.create_index('idx_financial_reports_type', ['report_type'], unique=False)
        batch_op.create_index('idx_financial_reports_period', ['period_start', 'period_end'], unique=False)
        batch_op.alter_column('created_at',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               nullable=True)
        batch_op.alter_column('average_check',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_master_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_company_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_net_profit',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_materials_cost',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('total_amount',
               existing_type=sa.Float(),
               type_=sa.REAL(),
               existing_nullable=False,
               existing_server_default=sa.text('(0.0)'))
        batch_op.alter_column('period_end',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('period_start',
               existing_type=sa.DateTime(),
               type_=sa.TEXT(),
               existing_nullable=True)
        batch_op.alter_column('report_type',
               existing_type=sa.String(length=50),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    with op.batch_alter_table('entity_history', schema=None) as batch_op:
        batch_op.add_column(sa.Column('deleted_at', sa.TIMESTAMP(), nullable=True))
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))

    with op.batch_alter_table('audit_log', schema=None) as batch_op:
        batch_op.add_column(sa.Column('version', sa.INTEGER(), server_default=sa.text('1'), nullable=False))
        batch_op.drop_index('idx_audit_timestamp')
        batch_op.drop_index('idx_audit_log_deleted_at')
        batch_op.alter_column('deleted_at',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               existing_nullable=True)
        batch_op.alter_column('timestamp',
               existing_type=sa.DateTime(),
               type_=sa.TIMESTAMP(),
               nullable=True,
               existing_server_default=sa.text('(CURRENT_TIMESTAMP)'))
        batch_op.alter_column('action',
               existing_type=sa.String(length=255),
               type_=sa.TEXT(),
               existing_nullable=False)
        batch_op.alter_column('id',
               existing_type=sa.INTEGER(),
               nullable=True,
               autoincrement=True)

    op.create_table('master_archives',
    sa.Column('id', sa.INTEGER(), nullable=True),
    sa.Column('master_id', sa.INTEGER(), nullable=False),
    sa.Column('file_path', sa.TEXT(), nullable=False),
    sa.Column('reason', sa.TEXT(), nullable=False),
    sa.Column('order_count', sa.INTEGER(), nullable=False),
    sa.Column('created_at', sa.TIMESTAMP(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.ForeignKeyConstraint(['master_id'], ['masters.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###
