"""Add parser_config table for Telethon parser configuration

Revision ID: add_parser_config
Revises: f9ec1face4e2
Create Date: 2025-01-27 10:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_parser_config'
down_revision: Union[str, None] = 'f9ec1face4e2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create parser_config table
    op.create_table(
        'parser_config',
        sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
        sa.Column('group_id', sa.Integer(), nullable=True, comment='ID Telegram-группы для мониторинга'),
        sa.Column('enabled', sa.Boolean(), nullable=False, comment='Включен ли парсер'),
        sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
        sa.PrimaryKeyConstraint('id')
    )

    # Create index
    op.create_index('idx_parser_config_enabled', 'parser_config', ['enabled'], unique=False)

    # Insert default configuration (disabled by default)
    op.execute(
        """
        INSERT INTO parser_config (group_id, enabled, created_at, updated_at)
        VALUES (NULL, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
        """
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_parser_config_enabled', table_name='parser_config')
    op.drop_table('parser_config')
    # ### end Alembic commands ###
