"""Add city_settings table for city-specific bot settings

Revision ID: add_city_settings
Revises: add_parser_config
Create Date: 2025-12-28 12:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'add_city_settings'
down_revision: Union[str, None] = 'add_parser_config'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Create city_settings table

    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'city_settings' not in tables:
        op.create_table(
            'city_settings',
            sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
            sa.Column('city_key', sa.String(length=100), nullable=False, comment='Ключ города (из ENV_FILE)'),
            sa.Column('profit_rate_threshold', sa.Float(), nullable=False, server_default='7000.0', comment='Порог суммы для процентной ставки 50/50 (в рублях)'),
            sa.Column('created_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.Column('updated_at', sa.DateTime(), server_default=sa.text('CURRENT_TIMESTAMP'), nullable=False),
            sa.PrimaryKeyConstraint('id'),
            sa.UniqueConstraint('city_key'),
            sa.CheckConstraint('profit_rate_threshold >= 0', name='chk_city_settings_profit_threshold')
        )

        # Create index
        op.create_index('idx_city_settings_city_key', 'city_settings', ['city_key'], unique=False)

        # Insert default configuration
        op.execute(
            """
            INSERT INTO city_settings (city_key, profit_rate_threshold, created_at, updated_at)
            VALUES ('default', 7000.0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            """
        )
    else:
        print("Table 'city_settings' already exists. Skipping creation.")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    tables = inspector.get_table_names()

    if 'city_settings' in tables:
        op.drop_index('idx_city_settings_city_key', table_name='city_settings')
        op.drop_table('city_settings')
    else:
        print("Table 'city_settings' does not exist. Skipping deletion.")
    # ### end Alembic commands ###
