"""Add SENIOR_MASTER role to user role constraint

Revision ID: f9ec1face4e2
Revises: 62892e258c24
Create Date: 2025-11-24 03:24:35.928714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ec1face4e2'
down_revision: Union[str, None] = '62892e258c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update users table constraint to include SENIOR_MASTER role
    
    # 1. Find the existing constraint name
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = inspector.get_check_constraints('users')
    
    constraint_name = 'chk_users_role'  # Default fallback
    
    # Try to find the actual constraint name by looking at its definition
    for c in constraints:
        sql = c['sqltext'].lower() if c['sqltext'] else ""
        # Look for a constraint that checks the 'role' column and contains 'admin'
        if 'role' in sql and 'admin' in sql:
            constraint_name = c['name']
            break
            
    print(f"Detected role constraint name: {constraint_name}")

    with op.batch_alter_table('users', schema=None) as batch_op:
        # Try to drop the constraint. If it doesn't exist (e.g. unnamed in SQLite and we couldn't find it),
        # we might catch an error, but usually batch_op handles dropping by name if we found it.
        try:
            batch_op.drop_constraint(constraint_name, type_='check')
        except (ValueError, sa.exc.OperationalError):
            print(f"Warning: Could not drop constraint {constraint_name}. It might not exist.")

        batch_op.create_check_constraint(
            'chk_users_role',
            (
                "role IN ('ADMIN', 'DISPATCHER', 'MASTER', 'SENIOR_MASTER', 'UNKNOWN') "
                "OR role LIKE '%,%'"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert users table constraint to exclude SENIOR_MASTER role
    
    # Find current constraint name (it should be chk_users_role if upgrade succeeded, but let's be safe)
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = inspector.get_check_constraints('users')
    
    constraint_name = 'chk_users_role'
    for c in constraints:
        sql = c['sqltext'].lower() if c['sqltext'] else ""
        if 'role' in sql and 'senior_master' in sql:
            constraint_name = c['name']
            break

    with op.batch_alter_table('users', schema=None) as batch_op:
        try:
            batch_op.drop_constraint(constraint_name, type_='check')
        except (ValueError, sa.exc.OperationalError):
            pass
            
        batch_op.create_check_constraint(
            'chk_users_role',
            "role IN ('ADMIN', 'DISPATCHER', 'MASTER', 'UNKNOWN') OR role LIKE '%,%'"
        )
    # ### end Alembic commands ###
