"""Add SENIOR_MASTER role to user role constraint

Revision ID: f9ec1face4e2
Revises: 62892e258c24
Create Date: 2025-11-24 03:24:35.928714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ec1face4e2'
down_revision: Union[str, None] = '62892e258c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update users table constraint to include SENIOR_MASTER role
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('chk_users_role', type_='check')
        batch_op.create_check_constraint(
            'chk_users_role',
            (
                "role IN ('ADMIN', 'DISPATCHER', 'MASTER', 'SENIOR_MASTER', 'UNKNOWN') "
                "OR role LIKE '%,%'"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert users table constraint to exclude SENIOR_MASTER role
    with op.batch_alter_table('users', schema=None) as batch_op:
        batch_op.drop_constraint('chk_users_role', type_='check')
        batch_op.create_check_constraint(
            'chk_users_role',
            "role IN ('ADMIN', 'DISPATCHER', 'MASTER', 'UNKNOWN') OR role LIKE '%,%'"
        )
    # ### end Alembic commands ###
