"""Add SENIOR_MASTER role to user role constraint

Revision ID: f9ec1face4e2
Revises: 62892e258c24
Create Date: 2025-11-24 03:24:35.928714

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f9ec1face4e2'
down_revision: Union[str, None] = '62892e258c24'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Update users table constraint to include SENIOR_MASTER role
    
    # 1. Find the existing constraint name
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = inspector.get_check_constraints('users')
    
    constraint_name = None
    
    print(f"Inspecting constraints on 'users' table: {constraints}")
    
    # Try to find the actual constraint name by looking at its definition
    for c in constraints:
        sql = c['sqltext'].lower() if c['sqltext'] else ""
        # Look for a constraint that checks the 'role' column and contains 'admin'
        if 'role' in sql and 'admin' in sql:
            constraint_name = c['name']
            print(f"Found matching constraint: {constraint_name}")
            break
            
    with op.batch_alter_table('users', schema=None) as batch_op:
        if constraint_name:
            print(f"Dropping constraint: {constraint_name}")
            batch_op.drop_constraint(constraint_name, type_='check')
        else:
            print("Warning: Could not find existing 'role' constraint to drop. Skipping drop.")

        batch_op.create_check_constraint(
            'chk_users_role',
            (
                "role IN ('ADMIN', 'DISPATCHER', 'MASTER', 'SENIOR_MASTER', 'UNKNOWN') "
                "OR role LIKE '%,%'"
            )
        )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Revert users table constraint to exclude SENIOR_MASTER role
    
    bind = op.get_bind()
    inspector = sa.inspect(bind)
    constraints = inspector.get_check_constraints('users')
    
    constraint_name = None
    for c in constraints:
        sql = c['sqltext'].lower() if c['sqltext'] else ""
        if 'role' in sql and 'senior_master' in sql:
            constraint_name = c['name']
            break

    with op.batch_alter_table('users', schema=None) as batch_op:
        if constraint_name:
            batch_op.drop_constraint(constraint_name, type_='check')
            
        batch_op.create_check_constraint(
            'chk_users_role',
            "role IN ('ADMIN', 'DISPATCHER', 'MASTER', 'UNKNOWN') OR role LIKE '%,%'"
        )
    # ### end Alembic commands ###
