"""Migrate hardcoded equipment type rules to specialization_rates table

Revision ID: migrate_hardcoded_rules
Revises: add_city_settings
Create Date: 2025-12-28 13:00:00.000000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'migrate_hardcoded_rules'
down_revision: Union[str, None] = 'add_city_settings'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Переносим жестко закодированные правила в БД

    bind = op.get_bind()

    # Проверяем, что записи еще не существуют
    result = bind.execute(
        sa.text("SELECT COUNT(*) FROM specialization_rates WHERE specialization_name IN ('Сантехника', 'Водонагреватели', 'Электрика')")
    )
    count = result.scalar()

    if count == 0:
        # Вставляем дефолтные правила
        op.execute(
            """
            INSERT INTO specialization_rates
                (specialization_name, master_percentage, company_percentage, is_default, created_at, updated_at)
            VALUES
                ('Сантехника', 50.0, 50.0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                ('Водонагреватели', 50.0, 50.0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP),
                ('Электрика', 50.0, 50.0, 0, CURRENT_TIMESTAMP, CURRENT_TIMESTAMP)
            """
        )
        print("✅ Добавлены дефолтные правила для Сантехники, Водонагревателей и Электрики")
    else:
        print("⚠️ Правила для специализаций уже существуют, пропускаем вставку")
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    # Удаляем добавленные правила
    op.execute(
        """
        DELETE FROM specialization_rates
        WHERE specialization_name IN ('Сантехника', 'Водонагреватели', 'Электрика')
        """
    )
    print("✅ Удалены правила для Сантехники, Водонагревателей и Электрики")
    # ### end Alembic commands ###
